/***********************************************************************/
/*                                                                     */
/*  FILE        :SerialT.c                                             */
/*  DATE        :Mon, Sep 26, 2016                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3687                                               */
/*                                                                     */
/*  This file is generated by WakuwakuP.                               */
/*                                                                     */
/*  github URL: https://github.com/WakuwakuP/Kadai_no_Hakaba           */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include <machine.h>

unsigned char vr_bk = 0;

void wait(unsigned int count);
void func_sci(void);

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void) {

	AD.ADCSR.BYTE =0x1E;

	IO.PMR1.BYTE = 0x08;

	SCI3_2.SCR3.BIT.RE = 0;				// 受信禁止
	SCI3_2.SCR3.BIT.TE = 0;				// 送信禁止
	SCI3_2.SMR.BYTE = 0x00;				// 調歩同期、クロック20MHz
	SCI3_2.BRR = 64;
	SCI3_2.TDR = 0x00;					// 送信データ初期化
	SCI3_2.SSR.BIT.OER = 0;				// 各種エラーのフラグを0に
	SCI3_2.SSR.BIT.FER = 0;
	SCI3_2.SSR.BIT.PER = 0;

	TZ0.TCR.BYTE = 0x23;				// GCAと一致でクリア&立ち上がりでカウント&プリスケーラ/8
	TZ0.POCR.BYTE = 0xF8;				// アクティブ設定
	TZ.TPMR.BYTE = 0x8E;				// PWMモード
	TZ.TOCR.BYTE = 0x0C;				// 初期出力設定
	TZ0.GRA = 256;						// MAX = 256
	TZ0.GRC = 0;

	wait(2);

	SCI3_2.SCR3.BIT.RE = 1;				// 受信許可
	SCI3_2.SCR3.BIT.RIE = 1;			// 受信割込許可
	SCI3_2.SCR3.BIT.TE = 1;				// 送信許可

	TZ.TOER.BIT.EC0 = 0;
	TZ0.TCNT = 0;
	TZ.TSTR.BIT.STR0 = 1;

	for(;;) {
		unsigned char vr_now;
		AD.ADCSR.BIT.ADST = 1;
		while (!AD.ADCSR.BIT.ADF);
		vr_now = AD.ADDRB >> 8;
		if(vr_bk != vr_now) {
			vr_bk = vr_now;
			SCI3_2.TDR = vr_bk;			// 相手に送信
		}
		AD.ADCSR.BIT.ADF = 0;
	}

}

// 待機関数
void wait(unsigned int count) {
	unsigned int i, j;

	for(i=0; i<=count; i++) {
		for(j=0; j<=2000; j++) {
		}
	}
}


void func_sci(void) {
	if(SCI3_2.SSR.BIT.RDRF == 1) {
		TZ0.GRC = SCI3_2.RDR;
		SCI3_2.SSR.BIT.RDRF = 0;
		SCI3_2.SSR.BIT.TDRE = 0;
	}
	else {
		SCI3_2.SSR.BIT.OER = 0;
		SCI3_2.SSR.BIT.FER = 0;
		SCI3_2.SSR.BIT.PER = 0;
	}
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
